services:
  finance-bot-web:
    build: web
    ports:
      - "16889:16889"

  finance-bot:
    build: .
    ports:
      - "16888:16888"
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"
