services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"

  web:
    build: web
    ports:
      - "16889:16889"

  api-server:
    build: .
    ports:
      - "16888:16888"
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"
