services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10.5
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js

  web:
    build: web
    ports:
      - "16889:16889"

  api-server:
    build: .
    ports:
      - "16888:16888"
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"
