services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass

  web:
    build: web
    ports:
      - "16889:16889"

  api-server:
    build: .
    ports:
      - "16888:16888"
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"
