services:
  web:
    build: web
    ports:
      - "16888:16888"

  crypto_loan:
    build: .
    ports:
      - "16910:16910"
    command: crypto_loan start
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"

  tw_stock_data_sync:
    build: .
    ports:
      - "16920:16920"
    command: tw_stock_data_sync start
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"

  schedule:
    build: .
    ports:
      - "16930:16930"
    command: schedule start
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"

  tw_stock_trade:
    build: .
    ports:
      - "16940:16940"
    command: tw_stock_trade start
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"

  super_bot:
    build: .
    ports:
      - "16950:16950"
    command: super_bot start
    volumes:
      - "./conf.d:/app/conf.d"
      - "./data:/app/data"
      - "./logs:/app/logs"
