from .base import StrategyBase
from .strategy_t1v0 import StrategyT1V0
from .strategy_t1v1 import StrategyT1V1
from .strategy_t2v0 import StrategyT2V0
from .strategy_t2v1 import StrategyT2V1
from .strategy_t2v2 import StrategyT2V2
from .strategy_t2v3 import StrategyT2V3
from .strategy_t2v4 import StrategyT2V4
from .strategy_t2v5 import StrategyT2V5
from .strategy_tnew import StrategyTNew
