core:
  schedule:
    crypto_loan:
      lending_task: '*/10 * * * *'
      update_status: '7 * * * *'
    data_sync:
      schedule_update:
        - '0 7 * * mon,tue,wed,thu,fri'
        - '0 11 * * sat'
    tw_stock_trade:
      execute_strategy: '7 * * * *'
    super_bot:
      daily_status:
        - '0 8 * * mon,tue,wed,thu,fri'
        - '0 12 * * sat'

  crypto_loan:
    api_key: <key>
    api_secret: <token>

  data_sync:
    updater:
      finmind:
        api_token: <token>
      finlab:
        api_token: <token>

  tw_stock_trade:
    shioaji:
      api_key: <key>
      api_secret: <token>
      person_id: <person_id>
      ca_password: <password>

  super_bot:
    telegram:
      chat_id: <chat_id>
      token: <token>

infrastructure:
  timezone: Asia/Taipei

  message_queue:
    url: <url>

  database:
    url: <url>
    async_url: <url>
  notification:
    telegram:
      chat_id: <chat_id>
      token: <token>
