server:
  service:
    crypto_loan:
      enabled: true
      schedule:
        lending_task: '*/10 * * * *'
        sending_stats:
          - '0 8 * * mon,tue,wed,thu,fri'
          - '0 12 * * sat,sun'
    data_sync:
      enabled: true
      schedule:
        schedule_update_task:
          - '0 8 * * mon,tue,wed,thu,fri'
          - '0 12 * * sat'
core:
  crypto_loan:
    api_key: <key>
    api_secret: <token>

  data_sync:
    shioaji:
      api_key: <key>
      api_secret: <token>

    updater:
      finmind:
        api_token: <token>
      finlab:
        api_token: <token>
infrastructure:
  timezone: Asia/Taipei
  database:
    url: <url>
    async_url: <url>
  notification:
    telegram:
      chat_id: <chat_id>
      token: <token>
