server:
  service:
    lending:
      enabled: true
      schedule:
        lending_task: '*/10 * * * *'
        sending_stats:
          - '0 8 * * mon,tue,wed,thu,fri'
          - '0 12 * * sat,sun'
    tw_stock:
      enabled: true
      schedule:
        schedule_update_task:
          - '0 8 * * mon,tue,wed,thu,fri'
          - '0 12 * * sat'
core:
  lending_bot:
    api_key: <key>
    api_secret: <token>

  tw_stock_manager:
    updater:
      finmind:
        api_token: <token>
      finlab:
        api_token: <token>
infrastructure:
  timezone: Asia/Taipei
  database:
    url: <url>
    async_url: <url>
  notification:
    telegram:
      chat_id: <chat_id>
      token: <token>
