core:
  schedule:
    crypto_loan:
      update_status: '0 7 * * *'
    tw_stock_data_sync:
      update_tw_stock: '0 0 * * *'
      update_tw_stock_prices: '0 0 * * *'
      update_monthly_revenue: '30 0 * * *'
      update_financial_statements: '0 1 * * *'
      update_db_cache: '0 6 * * *'
    tw_stock_trade:
      update_strategy_actions: '0 7 * * *'
      execute_trades: '0 9 * * mon,tue,wed,thu,fri'
    super_bot:
      send_daily_status:
        - '0 8 * * mon,tue,wed,thu,fri'
        - '0 12 * * sat'

  crypto_loan:
    api_key: <key>
    api_secret: <token>

  tw_stock_data_sync:
    updater:
      finmind:
        api_token: <token>
      finlab:
        api_token: <token>

  tw_stock_trade:
    shioaji:
      api_key: <key>
      secret_key: <token>
      person_id: <person_id>
      ca_password: <password>

  super_bot:
    telegram:
      chat_id: <chat_id>
      token: <token>

infrastructure:
  timezone: Asia/Taipei

  message_queue:
    url: <url>

  database:
    url: <url>
    async_url: <url>
  notification:
    telegram:
      chat_id: <chat_id>
      token: <token>
