server:
  timezone: Asia/Taipei
  service:
    lending: false
    tw_stock: false

lending:
  api_key: <token>
  api_secret: <token>
  schedule:
    lending_task: '* * * * *'
    sending_stats: '0 8 * * *'

tw_stock:
  database:
    url: <url>
  schedule:
    update_prices_task:
      - '0 8 * * tue,wed,thu,fri
      - '0 12 * * sat

  updater:
    findmind:
      api_token: <token>
    finlab:
      api_token: <token>

notification:
  telegram:
    chat_id: <url>
    token: <token>
