general:
  timezone: Asia/Taipei

ticker_db:
  database:
    url: <url>
  updater:
    findmind:
      api_token: <token>
    finlab:
      api_token: <token>

notification:
  telegram:
    chat_id: <url>
    token: <token>
