general:
  timezone: Asia/Taipei

lending:
  enabled: false
  api_key: <token>
  api_secret: <token>
  schedule:
    lending_task: '* * * * *'
    sending_stats: '0 8 * * *'

tw_stock:
  database:
    url: <url>
  updater:
    findmind:
      api_token: <token>
    finlab:
      api_token: <token>

notification:
  telegram:
    chat_id: <url>
    token: <token>
