### 更新股價資訊

POST {{host}}/tw-stock/update-prices-tasks
Content-Type: application/json

{
  "start": "2023-08-01",
  "end": "2023-08-01"
}

### 更新個股綜合財報

POST {{host}}/tw-stock/update-financial-statements-tasks
Content-Type: application/json

{
  "stock_id": "1101",
  "year": 2023,
  "season": 1
}

